### ISSUE TITLE
New toles now showing during user registration

### ISSUE THREAD

**Issue by laroned** [creativetimofficial/ct-argon-dashboard-pro-laravel#8]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [Yes] I am running the latest version
- [Yes ] I checked the documentation and found no answer
- [ Yes] I checked to make sure that this issue has not already been filed
- [ ] I'm reporting the issue to the correct repository (for multi-repository projects)

# Expected Behavior

Please describe the behavior you are expecting
When i add a new role, it should show up as an option when a new user is registering

# Current Behavior

What is the current behavior?

New role(s) is not showing up when a new user is registering

**Comment by Ghitu** [comment]
Hello @laroned. Thank you for using our products!
When creating a new role that role will only appear in the form where you (as an admin) create a new user. Is that the expected behavior you are describing?

Thanks
Alin

**Comment by laroned** [comment]
I would have thought when a new role is created a new user registering should be able to select the new role and register as the new role. 

Essentially what i would like to have have to new roles created and have new user of my website register as one of these two new roles

**Comment by Ghitu** [comment]
Hello @laroned. That is not how the functionality is built. 

It is done exactly how I described it on my last reply:
When creating a new role that role will only appear in the form where you (as an admin) create a new user. More than that, you need to define the level of access for that user role in the policies. Otherwise it will have the same level access as the member role.

If you need help with any of your projects, we're happy to get in touch. We do custom development for start-ups and companies across the globe (you can check out our portfolio here https://updivision.com/portfolio and some happy clients here https://updivision.com/testimonials). Don`t hesitate to drop us a line at office@updivision.com or by using our contact form (https://updivision.com/contact).
